### ISSUE TITLE
preload_models() got an unexpected keyword argument 'path

### ISSUE THREAD

**Issue by blastbeng** [serp-ai/bark-with-voice-clone#103]
Hi, 
I am trying to run the generation with a cloned voice, but i have this error

https://github.com/serp-ai/bark-with-voice-clone/blob/main/generate.ipynb

`TypeError: preload_models() got an unexpected keyword argument 'path'`

Looks like they removed the path argument from preload_models.

Does anyone else got this problem? How to preload my custom voice and generate audio with it?
Thanks

**Comment by phantomwork** [comment]
![image](https://github.com/user-attachments/assets/53f450f2-a9a9-44b1-87dc-1cb19c288b7d)

This is the [generation file from the bark](https://github.com/serp-ai/bark-with-voice-clone/blob/main/bark/generation.py)](https://github.com/serp-ai/bark-with-voice-clone/blob/main/bark/generation.py)\
And there absolutely exist "path" parameter.

I recommend you to clone the repo perfectly and give it a try again.\
Regards.

**Comment by blastbeng** [comment]
I have solved this by cloning and forking the repo and using the bark code provided inside the repo

Thanks

**Comment by phantomwork** [comment]
You are welcome.

**Comment by devinschumacher** [comment]
@blastbeng 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
