### ISSUE TITLE
Error: Output exceeds the size limit. Open the full output data in a text editor

### ISSUE THREAD

**Issue by kazhute** [serp-ai/bark-with-voice-clone#12]
On running the git I am getting following error. I have increased the Notebook › Output: Text Line Limit still getting the same error, is there a way to Trim Histories. I am not using GPU and was able to generate .npz file but voice cloning i am getting this error. Could anyone suggest a possible fix.

**Comment by binarycache** [comment]
I am sorry if I am assuming wrong, but this is not the error but just an indication that the error is much longer then what your IDE can display inline. You can simply click on "Open" and the text file containing the error will be opened.

Once you post the actual error some solution can be found.

**Comment by kazhute** [comment]
This is what I found in the error

{
	"name": "AssertionError",
	"message": "",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mAssertionError\u001b[0m                            Traceback (most recent call last)\nCell \u001b[1;32mIn[25], line 10\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[39m# generation with more control\u001b[39;00m\n\u001b[0;32m      2\u001b[0m x_semantic \u001b[39m=\u001b[39m generate_text_semantic(\n\u001b[0;32m      3\u001b[0m     text_prompt,\n\u001b[0;32m      4\u001b[0m     history_prompt\u001b[39m=\u001b[39mvoice_name,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m      7\u001b[0m     top_p\u001b[39m=\u001b[39m\u001b[39m0.95\u001b[39m,\n\u001b[0;32m      8\u001b[0m )\n\u001b[1;32m---> 10\u001b[0m x_coarse_gen \u001b[39m=\u001b[39m generate_coarse(\n\u001b[0;32m     11\u001b[0m     x_semantic,\n\u001b[0;32m     12\u001b[0m     history_prompt\u001b[39m=\u001b[39;49mvoice_name,\n\u001b[0;32m     13\u001b[0m     temp\u001b[39m=\u001b[39;49m\u001b[39m0.7\u001b[39;49m,\n\u001b[0;32m     14\u001b[0m     top_k\u001b[39m=\u001b[39;49m\u001b[39m50\u001b[39;49m,\n\u001b[0;32m     15\u001b[0m     top_p\u001b[39m=\u001b[39;49m\u001b[39m0.95\u001b[39;49m,\n\u001b[0;32m     16\u001b[0m )\n\u001b[0;32m     17\u001b[0m x_fine_gen \u001b[39m=\u001b[39m generate_fine(\n\u001b[0;32m     18\u001b[0m     x_coarse_gen,\n\u001b[0;32m     19\u001b[0m     history_prompt\u001b[39m=\u001b[39mvoice_name,\n\u001b[0;32m     20\u001b[0m     temp\u001b[39m=\u001b[39m\u001b[39m0.5\u001b[39m,\n\u001b[0;32m     21\u001b[0m )\n\u001b[0;32m     22\u001b[0m audio_array \u001b[39m=\u001b[39m codec_decode(x_fine_gen)\n\nFile \u001b[1;32mc:\\Users\\user\\OneDrive - Kenneth Inc\\Desktop\\bark-with-voice-clone-main\\bark-with-voice-clone-main\\bark\\generation.py:534\u001b[0m, in \u001b[0;36mgenerate_coarse\u001b[1;34m(x_semantic, history_prompt, temp, top_k, top_p, use_gpu, silent, max_coarse_history, sliding_window_len, model, use_kv_caching)\u001b[0m\n\u001b[0;32m    519\u001b[0m x_semantic_history \u001b[39m=\u001b[39m x_history[\u001b[39m\"\u001b[39m\u001b[39msemantic_prompt\u001b[39m\u001b[39m\"\u001b[39m]\n\u001b[0;32m    520\u001b[0m x_coarse_history \u001b[39m=\u001b[39m x_history[\u001b[39m\"\u001b[39m\u001b[39mcoarse_prompt\u001b[39m\u001b[39m\"\u001b[39m]\n\u001b[0;32m    521\u001b[0m \u001b[39massert\u001b[39;00m (\n\u001b[0;32m    522\u001b[0m     \u001b[39misinstance\u001b[39m(x_semantic_history, np\u001b[39m.\u001b[39mndarray)\n\u001b[0;32m    523\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mlen\u001b[39m(x_semantic_history\u001b[39m.\u001b[39mshape) \u001b[39m==\u001b[39m \u001b[39m1\u001b[39m\n\u001b[0;32m    524\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mlen\u001b[39m(x_semantic_history) \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m    525\u001b[0m     \u001b[39mand\u001b[39;00m x_semantic_history\u001b[39m.\u001b[39mmin() \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m    526\u001b[0m     \u001b[39mand\u001b[39;00m x_semantic_history\u001b[39m.\u001b[39mmax() \u001b[39m<\u001b[39m\u001b[39m=\u001b[39m SEMANTIC_VOCAB_SIZE \u001b[39m-\u001b[39m \u001b[39m1\u001b[39m\n\u001b[0;32m    527\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39misinstance\u001b[39m(x_coarse_history, np\u001b[39m.\u001b[39mndarray)\n\u001b[0;32m    528\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mlen\u001b[39m(x_coarse_history\u001b[39m.\u001b[39mshape) \u001b[39m==\u001b[39m \u001b[39m2\u001b[39m\n\u001b[0;32m    529\u001b[0m     \u001b[39mand\u001b[39;00m x_coarse_history\u001b[39m.\u001b[39mshape[\u001b[39m0\u001b[39m] \u001b[39m==\u001b[39m N_COARSE_CODEBOOKS\n\u001b[0;32m    530\u001b[0m     \u001b[39mand\u001b[39;00m x_coarse_history\u001b[39m.\u001b[39mshape[\u001b[39m-\u001b[39m\u001b[39m1\u001b[39m] \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m    531\u001b[0m     \u001b[39mand\u001b[39;00m x_coarse_history\u001b[39m.\u001b[39mmin() \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n\u001b[0;32m    532\u001b[0m     \u001b[39mand\u001b[39;00m x_coarse_history\u001b[39m.\u001b[39mmax() \u001b[39m<\u001b[39m\u001b[39m=\u001b[39m CODEBOOK_SIZE \u001b[39m-\u001b[39m \u001b[39m1\u001b[39m\n\u001b[0;32m    533\u001b[0m     \u001b[39mand\u001b[39;00m (\n\u001b[1;32m--> 534\u001b[0m         \u001b[39mround\u001b[39m(x_coarse_history\u001b[39m.\u001b[39mshape[\u001b[39m-\u001b[39m\u001b[39m1\u001b[39m] \u001b[39m/\u001b[39m \u001b[39mlen\u001b[39m(x_semantic_history), \u001b[39m1\u001b[39m)\n\u001b[0;32m    535\u001b[0m         \u001b[39m==\u001b[39m \u001b[39mround\u001b[39m(semantic_to_coarse_ratio \u001b[39m/\u001b[39m N_COARSE_CODEBOOKS, \u001b[39m1\u001b[39m)\n\u001b[0;32m    536\u001b[0m     )\n\u001b[0;32m    537\u001b[0m )\n\u001b[0;32m    538\u001b[0m x_coarse_history \u001b[39m=\u001b[39m _flatten_codebooks(x_coarse_history) \u001b[39m+\u001b[39m SEMANTIC_VOCAB_SIZE\n\u001b[0;32m    539\u001b[0m \u001b[39m# trim histories correctly\u001b[39;00m\n\n\u001b[1;31mAssertionError\u001b[0m: "
}

**Comment by francislabountyjr** [comment]
Was your sample less than 7 seconds? Anything longer seems to get truncated and causes issues.

**Comment by kazhute** [comment]
Sample length is 3 seconds.

**Comment by kazhute** [comment]
I found out that It works well in Colab but not on my local machine, I think there is an issue with my storage. I could successfully clone voice on colab and the output is good. 

could you tell more about these parameters, I tried to fine tune my speaker but the output either becomes gibberish or there is a long pause added before the speech.

# simple generation
audio_array = generate_audio(text_prompt, history_prompt=voice_name, text_temp=0.7, waveform_temp=0.7)

# generation with more control
x_semantic = generate_text_semantic(
    text_prompt,
    history_prompt=voice_name,
    temp=0.7,
    top_k=50,
    top_p=0.95,
)

x_coarse_gen = generate_coarse(
    x_semantic,
    history_prompt=voice_name,
    temp=0.7,
    top_k=50,
    top_p=0.95,
)
x_fine_gen = generate_fine(
    x_coarse_gen,
    history_prompt=voice_name,
    temp=0.5,
)

**Comment by devinschumacher** [comment]
@kazhute 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
