### ISSUE TITLE
I haven't seen any evidence voice cloning is possible at all.

### ISSUE THREAD

**Issue by CarlKenner** [serp-ai/bark-with-voice-clone#13]
Has anyone created a cloned .npz file that actually works?

**Comment by rexroth0619** [comment]
Not working for me. Created a .npz file using included notebook but keeps returning assertion error when trying to generate.

**Comment by DataScienceDec** [comment]
@rexroth0619 you can comment out the assert line and it should work. Keep in mind if you're using Colab you'll need to restart the runtime since the library is kept in cache. 

Results are still very ordinary for me

**Comment by rexroth0619** [comment]
> @rexroth0619 you can comment out the assert line and it should work. Keep in mind if you're using Colab you'll need to restart the runtime since the library is kept in cache.
> 
> Results are still very ordinary for me

Mind if I ask which line specifically? I notice assert function is run multiple times

**Comment by rexroth0619** [comment]
Nvm, commented out three lines according to error message. It runs, but the result is nothing like the sample I send in.

**Comment by 3dluvr** [comment]
I think we are missing something, and the developers need to give us more information whether this is even possible.

**Comment by francislabountyjr** [comment]
Samples need to be shorter, anything longer than 7 seconds seems to get truncated and causes the assertion errors to trigger. Best results seem to be shorter samples, around one sentence in length. We are working on finetuning, which I hope will give much better results.

**Comment by 3dluvr** [comment]
> Samples need to be shorter, anything longer than 7 seconds seems to get truncated and causes the assertion errors to trigger. Best results seem to be shorter samples, around one sentence in length. We are working on finetuning, which I hope will give much better results.

Can better results be had by using multiple samples on the same voice, and how can that be accomplished (repeated training)?

**Comment by rexroth0619** [comment]
> Samples need to be shorter, anything longer than 7 seconds seems to get truncated and causes the assertion errors to trigger. Best results seem to be shorter samples, around one sentence in length. We are working on finetuning, which I hope will give much better results.

Tried this and indeed no more assertion errors when making an .npz file, however when trying to generate new lines using that npz, assertion error appears again

**Comment by CRCODE22** [comment]
The generated voice clone is just the synthetic model with different voices it does not at all sound like the voice model.

**Comment by 3dluvr** [comment]
I guess we need the devs to disclose how to train own voices.

**Comment by polidox2** [comment]
what do you mean please by 

> @rexroth0619 you can comment out the assert line and it should work. Keep in mind if you're using Colab you'll need to restart the runtime since the library is kept in cache.
> 
> Results are still very ordinary for me

what do you mean by  comment out the assert line  ? do you mean cut the lenght of the audio?
i have a 1 minute audio lol and i am getting the  assertion errors

**Comment by 3dluvr** [comment]
> what do you mean please by
> 
> what do you mean by comment out the assert line ? do you mean cut the lenght of the audio? i have a 1 minute audio lol and i am getting the assertion errors
> 
> how can i "comment out"

https://github.com/serp-ai/bark-with-voice-clone/blob/main/bark/generation.py#L521

these are asserts - checks that fail execution if parameters are not met.

**Comment by MSDNAndi** [comment]
It worked for me - sometimes - but didn't do anything meaningful. The first time it generated garbage output and didn't sound like me, the second time it generated audio that didn't sound anything like me.

**Comment by FieldMarshallVague** [comment]
Not only does it not train my voice, it doesn't even train a consistent voice.  The voice output seems to change each time I play it.  Even though I am selecting the same voice name in the script.

This could be an issue with the Bark repo itself, because it's clearly not applying the trained NPZ in a consistent manner.

**Comment by 3dluvr** [comment]
We are just wasting our time on this, and I doubt developers will help in this area, seeing they might offer the feature through their online service.

Or they are protecting us from ourselves by not sharing this information...

**Comment by GeneralProtectionFault** [comment]
This "worked" fine for me, which is to say it generated an NPZ and I used the NPZ and got an AI voice.  Using the notebook from this repo still yielded a result, but it sucked.  I got somewhat better results when I stuck it in the bark infinity ui, but it was not a good imitation.  The best one was from a 3-second clip.  It's mentioned that longer isn't better, but I'm not sure why exactly.  But futzing with parameters does yield different outcomes, so I don't see what cause there is to question the overall possibility.  I don't know anything yet about what settings can be tweaked when creating the NPZ or when generating the audio, but quite curious about that.

**Comment by luther84** [comment]
I had a similar experience to Luke, I was able to generate the NPZ file
from a short 3ish second clip and then use it to generate voices. The new
NPZ file seemed to make a difference in the voices generated but calling it
"voice cloning" seems like a stretch. Any notable patterns in the parameter
changes that you saw?

**Comment by cixing** [comment]
> The generated voice clone is just the synthetic model with different voices it does not at all sound like the own trained voice model.

exactly

**Comment by francislabountyjr** [comment]
Voice cloning has been improved, check out the updated notebook for better clones

**Comment by devinschumacher** [comment]
@CarlKenner 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
