### ISSUE TITLE
Can't generate audio in Google Colab

### ISSUE THREAD

**Issue by NetyashaRoozi** [serp-ai/bark-with-voice-clone#2]
I was modifying the notebook so that it can run on colab and it seems like training works perfectly fine but I can't seem to get it to generate any sound. When I get to the generation cell I get this error

```
AssertionError                            Traceback (most recent call last)
[<ipython-input-6-18c098f645af>](https://localhost:8080/#) in <cell line: 5>()
      3      But I also have other interests such as playing tic tac toe.
      4 """
----> 5 audio_array = generate_audio(text_prompt, history_prompt="output")
      6 Audio(audio_array, rate=SAMPLE_RATE)

2 frames
[/usr/local/lib/python3.9/dist-packages/bark/generation.py](https://localhost:8080/#) in generate_coarse(x_semantic, history_prompt, temp, top_k, top_p, use_gpu, silent, max_coarse_history, sliding_window_len, model)
    475         x_semantic_history = x_history["semantic_prompt"]
    476         x_coarse_history = x_history["coarse_prompt"]
--> 477         assert (
    478             isinstance(x_semantic_history, np.ndarray)
    479             and len(x_semantic_history.shape) == 1

AssertionError:
```

not sure if I did something wrong with training or something installed incorrectly

**Comment by francislabountyjr** [comment]
Samples should be 7 seconds or less. In my limited testing, the short the sample, the better the generation

**Comment by devinschumacher** [comment]
@NetyashaRoozi 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
