### ISSUE TITLE
where audio.wav i should put?

### ISSUE THREAD

**Issue by wssb114** [serp-ai/bark-with-voice-clone#21]
i put it in bark-with-voice-clone\
but it cant be found

**Comment by polidox2** [comment]
make sure it's a .wav with the correct format
and just change audio_filepath = 'youraudio.wav'

it will definitely find it, but nevertheless you will have the assertion error once you move to block 10 for audio generation ;)

**Comment by devinschumacher** [comment]
@wssb114 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
