### ISSUE TITLE
NameError: name 'codes' is not defined

### ISSUE THREAD

**Issue by wssb114** [serp-ai/bark-with-voice-clone#22]
![image](https://user-images.githubusercontent.com/132080083/235308530-e4da356a-c9ce-4917-bc21-b53685f89034.png)

**Comment by devinschumacher** [comment]
@wssb114 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
