### ISSUE TITLE
No Model Download in new Version

### ISSUE THREAD

**Issue by 94awuna** [serp-ai/bark-with-voice-clone#25]
In the old Version everything worked fine, but I downloaded the newest version today and in generate.ipynb it won't download the models, it just keeps loading. Same with the generate_chunked.ipynb.

**Comment by devinschumacher** [comment]
@94awuna 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
