### ISSUE TITLE
Error when trying to export Audio

### ISSUE THREAD

**Issue by 94awuna** [serp-ai/bark-with-voice-clone#26]
I can generate Audio no problem, but if I try to export it, I get Errors.

The following Error in the generate.ipynb:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[1], line 4
      2 # save audio
      3 filepath = "/output/audio.wav" # change this to your desired output path
----> 4 write_wav(filepath, SAMPLE_RATE, audio_array)

NameError: name 'SAMPLE_RATE' is not defined

And when I use the generate_chunked.ipynb I get this Error:
FileNotFoundError                         Traceback (most recent call last)
Cell In[8], line 63
     60 audio_array = np.concatenate(all_parts, axis=-1)
     62 # save audio
---> 63 write_wav(out_filepath, SAMPLE_RATE, audio_array)
     65 # play audio
     66 Audio(audio_array, rate=SAMPLE_RATE)

File [c:\ProgramData\Anaconda3\lib\site-packages\scipy\io\wavfile.py:767](file:///C:/ProgramData/Anaconda3/lib/site-packages/scipy/io/wavfile.py:767), in write(filename, rate, data)
    765     fid = filename
    766 else:
--> 767     fid = open(filename, 'wb')
    769 fs = rate
    771 try:

FileNotFoundError: [Errno 2] No such file or directory: 'audio/audio.wav'

**Comment by baaoh** [comment]
it only likes forward-slash in directory names...

**Comment by francislabountyjr** [comment]
It's because the directory needs to exist before the file will save

**Comment by devinschumacher** [comment]
@94awuna 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
