### ISSUE TITLE
Clone_voice.ipynb generate_audio AssertionError

### ISSUE THREAD

**Issue by jkdntc** [serp-ai/bark-with-voice-clone#29]
I upload Clone_voice.ipynb to colab, got an error.

# simple generation
audio_array = generate_audio(text_prompt, history_prompt=voice_name, text_temp=0.7, waveform_temp=0.7)

100%|██████████| 100/100 [00:09<00:00, 10.93it/s]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-20-60d11f2388c8> in <cell line: 2>()
      1 # simple generation
----> 2 audio_array = generate_audio(text_prompt, history_prompt=voice_name, text_temp=0.7, waveform_temp=0.7)

2 frames
/usr/local/lib/python3.10/dist-packages/bark/generation.py in generate_coarse(x_semantic, history_prompt, temp, top_k, top_p, silent, max_coarse_history, sliding_window_len, use_kv_caching)
    565             and x_coarse_history.max() <= CODEBOOK_SIZE - 1
    566             and (
--> 567                 round(x_coarse_history.shape[-1] / len(x_semantic_history), 1)
    568                 == round(semantic_to_coarse_ratio / N_COARSE_CODEBOOKS, 1)
    569             )

AssertionError:

**Comment by jkdntc** [comment]
I found the reason：
To create a voice clone sample, you need an audio/text pair of less than 7 seconds. (limited testing shows better results with shorter samples (2-4 seconds))
my voice file is too long.

**Comment by francislabountyjr** [comment]
Voice cloning has been improved and I believe you should be able to use a sample up to  around13 seconds now (been testing on 8-9 second clips so not 100% sure on the upper limit)

**Comment by devinschumacher** [comment]
@jkdntc 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
