### ISSUE TITLE
Error while running Setup dataset cell in the file train_semantic.ipynb

### ISSUE THREAD

**Issue by lovishescobar** [serp-ai/bark-with-voice-clone#43]
`ImportError: cannot import name 'ALL_LAYERNORM_LAYERS' from 'transformers.pytorch_utils'

Running latest version of transformers

**Comment by devinschumacher** [comment]
@app/ 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
