### ISSUE TITLE
Random tail speech generated from fine-tuned model

### ISSUE THREAD

**Issue by renxiangnan** [serp-ai/bark-with-voice-clone#55]
Hi guys, I have recently tested the model fine-tuning on several certain speakers, I would say the improvement is significant comparing to the original base model. Thank you for this great work again. However, 

1. for all the fine-tuned model I tried, regardless the length of input text (even short as "Good morning"), the system will always try to generate the audio to the maximum length (15 seconds). This behavior leads to a lot of random generated contents at the end of the speech.
2. When using the fine-tuned model, this has been observed not just the fine-tuned speaker, but also the default speaker in Bark

I tried to modify the temperature and min eos probability, not helpful. Any thought or guidance would be great.

**Comment by devinschumacher** [comment]
@renxiangnan 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
