### ISSUE TITLE
voice cloning limitations

### ISSUE THREAD

**Issue by johnkpark** [serp-ai/bark-with-voice-clone#72]
I've been using the latest `clone_voice.ipynb`, but found that the output audio file does not get generated when the transcript is too long. From a few experiments, it looks like it would cut off where the audio output might be longer than 13 seconds i.e. 14 seconds is the longest output file that I was able to create. And sometimes when the transcript is too longer, the audio output would actually read something that's not in the transcript i.e. a jumble of words.

Is there an arbitrary limit imposed on the code? If so, is there a way to increase that? Sorry if I'm asking something that's already been documented, but when I searched for "limit" in the repo, I wasn't able to find anything related to my findings.

Also another question is that in the notebook, there is this comment about the input file as well:

```
audio_filepath = 'output.wav' # the audio you want to clone (under 13 seconds)
```

Is there a way to increase the 13 second limit on the input to improve the accuracy of cloning?

**Comment by gustrd** [comment]
Bark's context windows limits generations to 14 seconds, according to their repo.

It's a good idea do always aim at around 10 seconds to avoid problems.

You can break the string to be generated into chunks of around 128 characters (experimental number), and generate as a batch.

Here is an example code that I'm working on:

```
# This method serves as a tool to segment and streamline a large string into a list of more manageable and neatly formatted substrings, 
# each not exceeding 'max_length' characters.
def split_and_condense_string(input_string, max_length=128):
    final_result = []

    def split_by_char(subs, char):
        temp_result = []
        for sub in subs:
            split_strings = re.split(f'({char})', sub)
            temp_result.extend([x for x in split_strings if x])
        return [item for item in temp_result if item.strip()]

    def concatenate_small_strings(res):
        concatenated_result = []
        temp_str = ""
        for r in res:
            if len(temp_str) + len(r) <= max_length:
                temp_str += r
            else:
                concatenated_result.append(temp_str)
                temp_str = r
        if temp_str:
            concatenated_result.append(temp_str)
        return concatenated_result

    # Remove quebras de linha
    result = split_by_char([input_string], '\n')

    # Primeira divisão por pontos
    result = split_by_char(result, '\.')
    result = split_by_char(result, '!')
    result = split_by_char(result, '\?')

    # Segunda divisão por vírgulas, se necessário
    result = split_by_char(result, ',')

    # Concatenação de strings pequenas
    result = concatenate_small_strings(result)

    # Divisão em chunks de 128 caracteres, se necessário
    for res in result:
        if len(res) > max_length:
            for i in range(0, len(res), max_length):
                chunk = res[i:i+max_length]
                if chunk.strip():
                    final_result.append(re.sub(' +', ' ', chunk.strip()))
        else:
            if res.strip():
                final_result.append(re.sub(' +', ' ', res.strip()))

    return final_result

def generate_audio(input_text_list, processor, model):
    voice_preset = "C:\\_Models\\Cora.npz"

    inputs = processor(
        text=input_text_list,
        voice_preset=voice_preset,
        return_tensors="pt",
    )

    speech_values = model.generate(
        **inputs, 
        do_sample=True,
        fine_temperature = 0.6, 
        coarse_temperature = 0.6
        )

    return speech_values
```

**Comment by johnkpark** [comment]
Thanks for sharing @gustrd! Good to know that the limitation is coming from the Bark model.

**Comment by johnkpark** [comment]
BTW, also found this in the Bark repo for anyone who's interested in a long-form generation: https://github.com/suno-ai/bark/blob/main/notebooks/long_form_generation.ipynb

**Comment by devinschumacher** [comment]
@johnkpark 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
