### ISSUE TITLE
No GPU being used.

### ISSUE THREAD

**Issue by egemenyildirim90** [serp-ai/bark-with-voice-clone#82]
![image](https://github.com/serp-ai/bark-with-voice-clone/assets/19346980/82453462-fb63-49ed-9657-1587b7fe90ef)

Even though CUDA and torch is installed, I'm getting this error. It says the GPU can't be used. What could be the reason?

**Comment by egemenyildirim90** [comment]
I found the fix. The correct CUDA version was not installed. It got resolved when I installed version 11.7.

**Comment by devinschumacher** [comment]
@egemenyildirim90 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
