### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by kevinambrose** [serp-ai/bark-with-voice-clone#90]
I'm getting this error when using the test_models.ipynb with use_rvc set to True

`TypeError                                 Traceback (most recent call last)
Cell In[7], line 17
      1 preload_models(
      2     text_use_gpu=True,
      3     text_use_small=False,
   (...)
     13     path="models"
     14 )
     16 if use_rvc:
---> 17     from rvc_infer import get_vc, vc_single
     18     get_vc(rvc_path, device, is_half)

File ~\Documents\GitHub\bark-with-voice-clone\rvc_infer.py:114
    112 sys.path.append(os.path.join(now_dir,"Retrieval-based-Voice-Conversion-WebUI"))
    113 from vc_infer_pipeline import VC
--> 114 from infer.lib.infer_pack.models import SynthesizerTrnMs256NSFsid, SynthesizerTrnMs256NSFsid_nono, SynthesizerTrnMs768NSFsid, SynthesizerTrnMs768NSFsid_nono
    115 from fairseq import checkpoint_utils
    116 from scipy.io import wavfile

File ~\Documents\GitHub\bark-with-voice-clone\Retrieval-based-Voice-Conversion-WebUI\infer.py:10
      8 from infer_pack.models import SynthesizerTrnMs256NSF as SynthesizerTrn256
      9 from scipy.io import wavfile
---> 10 from fairseq import checkpoint_utils
     11 import scipy.signal as signal
     12 from vc_infer_pipeline import VC

File ~\AppData\Local\anaconda3\envs\bark\lib\site-packages\fairseq\__init__.py:40
     38 import fairseq.optim.lr_scheduler  # noqa
     39 import fairseq.pdb  # noqa
---> 40 import fairseq.scoring  # noqa
     41 import fairseq.tasks  # noqa
     42 import fairseq.token_generation_constraints  # noqa

File ~\AppData\Local\anaconda3\envs\bark\lib\site-packages\fairseq\scoring\__init__.py:34
     29     @abstractmethod
     30     def result_string(self) -> str:
     31         pass
---> 34 _build_scorer, register_scorer, SCORER_REGISTRY, _ = registry.setup_registry(
     35     "--scoring", default="bleu"
     36 )
     39 def build_scorer(choice, tgt_dict):
     40     _choice = choice._name if isinstance(choice, DictConfig) else choice

TypeError: cannot unpack non-iterable NoneType object`

**Comment by devinschumacher** [comment]
@kevinambrose 

We just launched our follow up to BARK -- an AI Voice Cloner Desktop App (runs locally, offline, super realistic voice cloning, data privacy, no coding needed)

👉 Check it out: https://github.com/serpapps/ai-voice-cloner
